### PR TITLE
Add new Get functions

### PR DESCRIPTION
**Pull request by mpuckett159**
Adding new get functions from other API endpoints to round out the types of objects that can be pulled from a vRA 8.x endpoint.

Fixed some API URIs to be compliant with the Swagger spec. It looks like the API responds with no issues to the currently set URI, but for the sake of clarity updating them to follow the current spec outlined by VMware docs.

List of new functions added:

- Get-vRABlueprint
- Get-vRACatalogItem
- Get-vRAContentSource
- Get-vRADeployment
- Get-vRANetworkProfile

List of functions with fixed API URI:

- Get-vRACloudAccount
- Get-vRACloudZone
- Get-vRAProject

### CODE REVIEW

**Comment by mpuckett159** [comment]
Included some more functions to finish out covering the IaaS API endpoints:

- Get-vRAExternalNetworkIPRange
- Get-vRALoadBalancer
- Get-vRANetwork
- Get-vRANetworkDomain
- Get-vRANetworkIPRange
- Get-vRARegion
- Get-vRASecurityGroup
- Get-vRAStorageProfile
- Get-vRATag

**Comment by Stevio54** [comment]
Starting to infringe on some of the work I am doing but haven't merged yet there sir ;) heh, but this is looking good. Will look closer when I have time

**Review by jonathanmedd — CHANGES_REQUESTED** [review]
Looks good to me - thanks for the excellent contribution. Just need

- Finish off Get-vRAFabricAzureStorageAccount
- One of the other reviewers to test the functions, I no longer have access to a vRA Cloud instance

Then it can be merged

**Comment by mpuckett159** [comment]
Better late (and a whole different version) than never I suppose.

**Review by Stevio54 — APPROVED** [review]
I think this all looks great. Good work!

**Comment by mpuckett159** [comment]
Oops, I missed the request for the new function, I'll add that ASAP.

**Comment by mpuckett159** [comment]
Sorry about that completely forgot I even created that skeleton function and never filled it out haha.

**Review by jonathanmedd — APPROVED** [review]
LGTM

**Pull request merged**
