### PR TITLE
Feature content management service

### PR DESCRIPTION
**Pull request by chelnak**
Expands support for Content-Management-Service to include Content API

### CODE REVIEW

**Comment by jonathanmedd** [comment]
Is this file still supposed to be in the psd1? It's causing the module to not load

 'Functions\Public\Export-vRAContentPackage.psm1',

**Comment by jonathanmedd** [comment]
Darn it, I thought you had just forgotten to update the manifest, but perhaps you have done it elsewhere already?

**Comment by jonathanmedd** [comment]
Just need to sort that out (maybe I need to revert my commit for it?) - otherwise all looks good, great job!

**Comment by chelnak** [comment]
Yeah you are right. You need to revert your changes to the manifest file. This is because the manifest in develop is technically ahead of this branch.

Think the steps should be:

- Revert commit
- Merge development in to this branch as it is ahead (because of 1.4.0 changes)
- Merge PR - This branch in to development
- Run build.ps1 to update docs & update documentation
- Bump manifest version & appveyor build version (1.5.0 or what ever we agree)

When i'm testing in a feature branch I use ```.\build.ps1 -Task UpdateModuleManiest``` so i can test the module but never commit changes to the manifest. The manifest functions should only ever be updated by the build script in the development branch. Version is manual at the moment.

I know I still need to document all of this. Will make a start on it when I return :-)

**Comment by jonathanmedd** [comment]
OK, yeah I figured that after I had committed it :-(

Let's figure it out when you get back......

**Pull request merged**
